# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-19 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('\u0421\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437', '\u0421\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437'), ('\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u043a\u0443\u0440\u044a\u0435\u0440\u043e\u043c', '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u043a\u0443\u0440\u044a\u0435\u0440\u043e\u043c'), ('\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u041d\u043e\u0432\u043e\u0439 \u041f\u043e\u0447\u0442\u043e\u0439', '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u041d\u043e\u0432\u043e\u0439 \u041f\u043e\u0447\u0442\u043e\u0439')], default='\u0421\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
