# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-29 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_auto_20190429_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d'),
        ),
    ]
