# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-29 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0013_auto_20190429_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date',), 'verbose_name': '\u0417\u0430\u043a\u0430\u0437', 'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d'),
        ),
    ]
