# Generated by Django 2.2.1 on 2019-05-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0018_auto_20190507_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.CharField(max_length=20, verbose_name='USD - Dollars')),
                ('uah', models.CharField(max_length=20, verbose_name='UAH - Гривна')),
            ],
        ),
    ]
