# Generated by Django 2.2.1 on 2019-05-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0019_changeproductprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeProductPrice',
        ),
    ]
