# Generated by Django 2.2.1 on 2019-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0020_delete_changeproductprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=5, verbose_name='Объем'),
        ),
    ]
